apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: propertystake-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - propertystake.cybonix.fr
      secretName: auth-service-tls
  rules:
    - host: propertystake.cybonix.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: istio-ingressgateway
                port:
                  number: 2000

