apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-routes
spec:
  hosts:
    - "*"
  gateways:
    - api-gateway
  http:
    - match:
        - uri:
            prefix: /users
      route:
        - destination:
            host: user-service
            port:
              number: 3001
    - match:
        - uri:
            prefix: /properties
      route:
        - destination:
            host: property-service
            port:
              number: 3002
    - match:
        - uri:
            prefix: /investments
      route:
        - destination:
            host: investment-service
            port:
              number: 3003
    - match:
        - uri:
            prefix: /payments
      route:
        - destination:
            host: payment-service
            port:
              number: 3004
    - match:
        - uri:
            prefix: /notifications
      route:
        - destination:
            host: notification-service
            port:
              number: 3005
