apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: propertystake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/mr-r-b0t/cloud-project-auth-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: JWT_SECRET
              value: "VEpQQzZkZ0YhP0tCeUBoOUNBNWFQcG84IzZ6c1BRSGVxSlgmNGJiYmFDaW4/WEwjTkRiQUtZNGZKQjhoOGJHR2FnQ2lHR1BScVRoM2EmTUdMWXNhQ01CTGM/I0t6P05KRWIkc2doSERiQVNlJmtqZHI0SFhkSmRA"
            - name: DATABASE_URL
              value: "postgresql://ssaproject:ssapassword@postgres-service:5432/ssa"
      imagePullSecrets:
        - name: ghcr-login-secret
---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: propertystake
spec:
  selector:
    app: auth-service
  ports:
    - port: 80
      targetPort: 3000