apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: investment-service
  template:
    metadata:
      labels:
        app: investment-service
    spec:
      containers:
        - name: investment-service
          image: ghcr.io/mr-r-b0t/cloud-project-investment-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              value: "postgresql://ssaproject:ssapassword@postgres-service:5432/ssa"
            - name: USER_SERVICE_URL
              value: "http://user-service:3001"
            - name: PROPERTY_SERVICE_URL
              value: "http://property-service:3002"

---

apiVersion: v1
kind: Service
metadata:
  name: investment-service
spec:
  selector:
    app: investment-service
  ports:
    - port: 3002
      targetPort: 3002