apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: propertystake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ghcr.io/mr-r-b0t/cloud-project-notification-service:latest

          ports:
            - containerPort: 3005
          env:
            - name: NODE_ENV
              value: production
      imagePullSecrets:
        - name: ghcr-login-secret
---

apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: propertystake
spec:
  selector:
    app: notification-service
  ports:
    - port: 3005
      targetPort: 3005
      nodePort: 2000

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: notification-service-proxy
spec:
    hosts:
        - "*"
    gateways:
        - microservice-gateway
    http:
        - match:
          - uri:
              prefix: /notification/
          rewrite:
              uri: /
        - route:
            - destination:
                host: notification-service
                port:
                    number: 3005
