apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: propertystake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ghcr.io/mr-r-b0t/cloud-project-payment-service:latest
      imagePullSecrets:
        - name: ghcr-login-secret
          ports:
            - containerPort: 3004
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              value: "postgresql://ssaproject:ssapassword@postgres-service:5432/ssa"
            - name: USER_SERVICE_URL
              value: "http://user-service:3001"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:3005"

---

apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: propertystake
spec:
  selector:
    app: payment-service
  ports:
    - port: 3004
      targetPort: 3004

