apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-service
  namespace: propertystake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: property-service
  template:
    metadata:
      labels:
        app: property-service
    spec:
      containers:
        - name: property-service
          image: ghcr.io/mr-r-b0t/cloud-project-property-service:lastest
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              value: "postgresql://ssaproject:ssapassword@postgres-service:5432/ssa"
            - name: INVESTMENT_SERVICE_URL
              value: "http://investment-service:3003"
      imagePullSecrets:
        - name: ghcr-login-secret
---

apiVersion: v1
kind: Service
metadata:
  name: property-service
  namespace: propertystake
spec:
  selector:
    app: property-service
  ports:
    - port: 3002
      targetPort: 3002

