#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: propertystake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/mr-r-b0t/cloud-project-user-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              value: "postgresql://ssaproject:ssapassword@postgres-service:5432/ssa"
      imagePullSecrets:
        - name: ghcr-login-secret
---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: propertystake
spec:
  selector:
    app: user-service
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 2000

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-service-proxy
spec:
    hosts:
        - "*"
    gateways:
        - microservice-gateway
    http:
        - match:
            - uri:
                prefix: /user/
        - route:
            - destination:
                host: user-service
                port:
                    number: 3001
