#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: propertystake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/mr-r-b0t/cloud-project-user-service:latest
          imagePullSecrets:
            - name: ghcr-login-secret
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              value: "postgresql://ssaproject:ssapassword@postgres-service:5432/ssa"

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: propertystake
spec:
  selector:
    app: user-service
  ports:
    - port: 3001
      targetPort: 3001

