name: Build & Push Docker Image

permissions:
  packages: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build investement service
        run: docker build -t ghcr.io/glyps/Mr-R-b0t/Cloud-Project:investment-service ./investment-service

      - name: build notification service
        run: docker build -t ghcr.io/glyps/Mr-R-b0t/Cloud-Project:notification-service ./notification-service

      - name: build payment service
        run: docker build -t ghcr.io/glyps/pMr-R-b0t/Cloud-Project:payment-service ./payment-service

      - name: build property service
        run: docker build -t ghcr.io/Mr-R-b0t/Cloud-Project:property-service ./property-service

      - name: build user service
        run: docker build -t ghcr.io/Mr-R-b0t/Cloud-Project:user-service ./user-service

      - name: login to ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: push to ghrc
        run: docker push ghcr.io/glyps/Mr-R-b0t/Cloud-Project:investment-service && 
          docker push ghcr.io/glyps/Mr-R-b0t/Cloud-Project:notification-service && 
          docker push ghcr.io/glyps/Mr-R-b0t/Cloud-Project:payment-service && 
          docker push ghcr.io/glyps/Mr-R-b0t/Cloud-Project:property-service && 
          docker push ghcr.io/glyps/Mr-R-b0t/Cloud-Project:user-service


